import { interceptFunction, isString, restoreFunction, RumEventType } from "@arms/rum-core"; import { getCurView } from "../../utils/view"; var ExceptionCollector =/*#__PURE__*/function () {
   function a() {
      var a = this; this.name = "exception-collector", this.ctx = void 0, this.sendEvent = void 0, this.uniError = function (b) { a.errorHandle(b, "uni.onError") }, this.onError = function (b) { a.errorHandle(b, "onError") }, this.onUnhandledRejection = function (b) {
         if (b) {
            var c = b.reason; if (c) {
               var d = c.errMsg;// 对 Uniapp 内置错误进行解析
               if (d && isString(d)) { c = new Error(d), c.name = "", c.stack = ""; for (var e, f = ["navigateTo", "redirectTo", "appLaunch", "switchTab", "getLocation", "onLocationChange"], g = 0, h = f; g < h.length; g++)if (e = h[g], d.startsWith(e)) { c.name = e; break } c.name || (c.name = d.split(":")[0]) } a.errorHandle(c, "onUnhandledRejection")
            }
         }
      }, this.errorHandle = function (b, c) { void 0 === c && (c = ""); console.log("[ARMS DEBUG] errorHandle 被调用，source:", c, "error:", b); var d, e, f, g, h, i, j = getCurView(a.ctx); if (b instanceof Object) { if (d = b.name, e = b.message, f = b.filename || b.fileName, g = b.stack, h = b.lineno || b.lineNumber, i = b.colno || b.columnNumber, b.error instanceof Error) { var k = b.error; d = k.name, e = k.message, g = k.stack } } else if ("string" == typeof b) { g = b; var l = a.getErrorByStack(b); if (l) { d = l.name, e = l.message } else { var m = b.match(/Error:\s*(.+)/); if (m) { d = "Error", e = m[1] } else { d = "UnknownError", e = b.substring(0, 200) } } } console.log("[ARMS DEBUG] 解析后的错误信息 - name:", d, "message:", e); d && e ? (console.log("[ARMS DEBUG] 准备发送错误事件"), a.sendEvent({ event_type: RumEventType.EXCEPTION, source: c, type: "error", name: d, message: e, file: f, stack: g, line: h, column: i, times: 1, view: j })) : console.log("[ARMS DEBUG] 错误信息不完整，跳过发送 - name:", d, "message:", e) }
   } var b = a.prototype; return b.setup = function (a, b) { this.ctx = a, this.sendEvent = b, this.hackOrigin() }, b.hackOrigin = function () { var a = this, b = this.ctx.getConfig(), c = b.collectors, d = void 0 === c ? {} : c; console.log("[ARMS DEBUG] hackOrigin 开始，配置:", d); if (!1 !== d.jsError) try { console.log("[ARMS DEBUG] 注册 uni.onError"); uni.onError(this.uniError); console.log("[ARMS DEBUG] uni.onError 注册成功"); typeof global !== "undefined" && global.addEventListener ? (console.log("[ARMS DEBUG] 注册 global.addEventListener"), global.addEventListener("error", this.onError), global.addEventListener("unhandledrejection", this.onUnhandledRejection), console.log("[ARMS DEBUG] global listeners 注册成功")) : console.log("[ARMS DEBUG] global.addEventListener 不可用") } catch (b) { console.error("[ARMS DEBUG] 注册失败:", b) } !1 !== d.consoleError ? (console.log("[ARMS DEBUG] 拦截 console.error"), interceptFunction(console, "error", function (b) { console.log("[ARMS DEBUG] console.error 被调用，参数:", b); a.errorHandle(b, "console.error") }), console.log("[ARMS DEBUG] console.error 拦截成功")) : console.log("[ARMS DEBUG] consoleError 监控已禁用") }, b.getErrorByStack =/**
   * 根据stack获取Error信息
   * TODO: 增加基于Stack解析filename和lineNumber的能力
   * @param stack
   * @returns
   */function (a) { void 0 === a && (a = ""); var b = a.split("\n"); if (!(2 > b.length)) for (var c = 1; c < b.length; c++)if (b[c].trim().startsWith("at ")) { var d = b[c - 1], e = d.indexOf(": "); return { name: d.substring(0, e), message: d.substring(e + 2) } } }, b.destroy = function () { typeof global !== "undefined" && global.console && restoreFunction(global.console, "error") }, a
}(); export { ExceptionCollector as default };
